#!/bin/sh

GREP="grep -Hn --color=always"

#$GREP "IOMeter" *.tex
#$GREP "IOmeter" *.tex
#$GREP -i "[^\\]dede" *.tex | grep -v '\\newcommand'
#$GREP " ~\\|^~" *.tex
#$GREP "[0-9][GMK][^B]" *.tex
exit 0
